### PR TITLE
Add Cell Disk-Cleanup scheduling topic

### PR DESCRIPTION
**Pull request by glestaris**
* Copied and adjusted from PCF docs.

Can you please help me link to this topic?

### CODE REVIEW

**Comment by pspinrad** [comment]
Hey @glestaris -- thanks for the contribution!  Let's def link to it, but need to figure out where's best-- do you think it's a CF Operator type topic, along with managing numbers of containers, setting up logging, stuff like that?

Also, you refer to options that CF provides, like **Never clean up the Cell Disk** etc. -- where/how do you see these?

Thanks!

**Comment by glestaris** [comment]
Hey @pspinrad,

Yes, it's a CF operator type topic. It's up to CF operators to decide how they'd like to manage disk space on their cells. 

The three options refer to the three possible values the `garden.graph_cleanup_threshold_in_mb` BOSH property can take: `-1`, `0` and a positive number. The options that are listed in the `#options` section are just the semantics of the values. So, **Never clean up the Cell Disk** maps to setting the BOSH property to `0` (which is later discussed in `#applying-configuration`.)

I was trying to separate the description of the options and the recommandations with the part of actually applying the configuration.

Feel free to move things around if you reckon it would make it easier to read/understand.

**Comment by pspinrad** [comment]
Thanks @glestaris -- makes total sense, and good to confirm that **Never clean up** etc. don't appear in any PCF GUI that I didn't know about.

**Comment by glestaris** [comment]
Hey @pspinrad. I probably misled you. These words do appear in the PCF OpsMan UI: https://docs.pivotal.io/pivotalcf/1-11/opsguide/config-cell-cleanup.html. I used them in the CFF docs to represent the BOSH property options. Should we rephrase to avoid the association?

**Comment by pspinrad** [comment]
Oh, thanks for the pointer and sorry for misunderstanding-- I'll put that Ops Man GUI part in a snippet so it doesn't appear in OSS version of topic, and find a place for it that makes sense for both CF and PCF.

**Comment by pspinrad** [comment]
Sorry, was confused-- PCF-relevant version of topic was already in PCF, which is what you meant by "Copied and adjusted from PCF docs." :-P

So, this is only relevant to Docker containers in CF, right?

**Comment by glestaris** [comment]
No, GC threshold applies to all containers (Docker and buildpack-based). It's just that the topic comes up mostly with Docker containers.

I PRed PCF docs again (https://github.com/pivotal-cf/docs-ops-guide/pull/42) and dropped 'Docker' from the title since this has confused people in the past (as it's not only related to Docker).

**Pull request merged**
